
log_format dc_json escape=json '{"time":"$time_iso8601","remote_addr":"$remote_addr","remote_port":"$remote_port","server_name":"$server_name","server_port":"$server_port","request_method":"$request_method","request_uri":"$request_uri","status":$status,"body_bytes_sent":$body_bytes_sent,"request_time":$request_time,"upstream_addr":"$upstream_addr","upstream_response_time":"$upstream_response_time","http_user_agent":"$http_user_agent","http_referer":"$http_referer","scheme":"$scheme","ssl_protocol":"$ssl_protocol"}';


# 1: nettech.uz:80 -> http://10.100.10.240:80
server {
    listen 80;
    server_name nettech.uz;

    location ^~ /.well-known/acme-challenge/ {
        root /tmp/certbot;
    }

    location / {
        access_log /Users/macbookpro/PycharmProjects/DomainController/dev_access.json dc_json;
        proxy_pass http://10.100.10.240:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_read_timeout 3600;
        proxy_send_timeout 3600;
    }
}


# 2: shop.nettech.uz:80 -> http://10.100.10.241:80
server {
    listen 80;
    server_name shop.nettech.uz;

    location ^~ /.well-known/acme-challenge/ {
        root /tmp/certbot;
    }

    location / {
        access_log /Users/macbookpro/PycharmProjects/DomainController/dev_access.json dc_json;
        proxy_pass http://10.100.10.241:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_read_timeout 3600;
        proxy_send_timeout 3600;
    }
}
