#!/usr/bin/env bash
# DomainController — установка на свежую Ubuntu 24.04.
#
# Идемпотентный: повторный запуск не ломает существующую установку.
# Требует sudo. Код должен быть уже скопирован в /opt/domain-controller
# (или в INSTALL_DIR).
#
# Использование:
#   sudo ./deploy/install.sh
#
# Бэкенд БД — PostgreSQL (всегда). SQLite в production не поддерживается.
# Скрипт создаёт PG-юзера, БД, генерирует случайный пароль и пишет DATABASE_URL
# в .env. Если PG уже установлен и юзер/БД существуют — переиспользуются.
#
# После установки:
#   1. Отредактировать /opt/domain-controller/.env (DC_PANEL_SECRET и DATABASE_URL
#      уже сгенерированы)
#   2. Отредактировать /etc/nginx/sites-available/domain-panel.conf (whitelist IP)
#   3. flask --app /opt/domain-controller/app.py create-user <username>
#   4. sudo systemctl enable --now domain-controller

set -euo pipefail

INSTALL_DIR="${INSTALL_DIR:-/opt/domain-controller}"
PANEL_PORT="${PANEL_PORT:-8080}"
PG_DB_NAME="${PG_DB_NAME:-dc}"
PG_DB_USER="${PG_DB_USER:-dc_user}"

log() { printf '\033[1;34m[install]\033[0m %s\n' "$*"; }
die() { printf '\033[1;31m[install] %s\033[0m\n' "$*" >&2; exit 1; }

[[ $EUID -eq 0 ]] || die "Запускайте через sudo."
[[ -f "$INSTALL_DIR/app.py" ]] || die "Код не найден в $INSTALL_DIR. Скопируйте сначала."

log "1/9 Пакеты: nginx, certbot, python3-venv, logrotate, fail2ban, openssl, postgresql"
apt-get update
DEBIAN_FRONTEND=noninteractive apt-get install -y \
    nginx python3 python3-venv python3-pip \
    certbot logrotate fail2ban openssl \
    postgresql postgresql-contrib libpq-dev

log "2/9 Python virtualenv + зависимости"
cd "$INSTALL_DIR"
if [[ ! -d venv ]]; then
    python3 -m venv venv
fi
./venv/bin/pip install --upgrade pip wheel
./venv/bin/pip install -r requirements.txt

log "3/9 PostgreSQL — юзер и БД"
systemctl enable --now postgresql
PG_DB_PASS=""
# Идемпотентно: создаём юзера и БД только если их нет
if ! sudo -u postgres psql -tAc "SELECT 1 FROM pg_roles WHERE rolname='$PG_DB_USER'" | grep -q 1; then
    PG_DB_PASS=$(python3 -c "import secrets; print(secrets.token_urlsafe(32))")
    sudo -u postgres psql -c "CREATE USER $PG_DB_USER WITH PASSWORD '$PG_DB_PASS';"
    log "   -> создан пользователь $PG_DB_USER (пароль сгенерирован, попадёт в .env)"
else
    log "   -> пользователь $PG_DB_USER уже существует (пароль возьмите из существующего .env)"
fi
if ! sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname='$PG_DB_NAME'" | grep -q 1; then
    sudo -u postgres psql -c "CREATE DATABASE $PG_DB_NAME OWNER $PG_DB_USER ENCODING 'UTF8' TEMPLATE template0;"
    log "   -> создана БД $PG_DB_NAME"
else
    log "   -> БД $PG_DB_NAME уже существует"
fi

log "4/9 .env"
if [[ ! -f "$INSTALL_DIR/.env" ]]; then
    cp deploy/env.example "$INSTALL_DIR/.env"
    secret=$(python3 -c "import secrets; print(secrets.token_urlsafe(64))")
    sed -i "s|REPLACE_ME_WITH_A_LONG_RANDOM_STRING|$secret|" "$INSTALL_DIR/.env"
    if [[ -n "$PG_DB_PASS" ]]; then
        db_url="postgresql+psycopg2://$PG_DB_USER:$PG_DB_PASS@127.0.0.1:5432/$PG_DB_NAME"
        sed -i "/^DATABASE_URL=/d; /^#DATABASE_URL=/d" "$INSTALL_DIR/.env"
        echo "DATABASE_URL=$db_url" >> "$INSTALL_DIR/.env"
        log "   -> DATABASE_URL записан в .env"
    else
        log "   -> WARNING: PG-юзер уже существовал. Прописать DATABASE_URL в .env вручную."
    fi
    chown root:root "$INSTALL_DIR/.env"
    chmod 600 "$INSTALL_DIR/.env"
    log "   -> создан $INSTALL_DIR/.env с автогенерённым DC_PANEL_SECRET"
else
    log "   -> $INSTALL_DIR/.env уже существует, не перезаписываем"
fi

log "5/9 ACME webroot для certbot"
mkdir -p /var/www/certbot
chown -R www-data:www-data /var/www/certbot

log "6/9 Nginx — подключить conf.d/domain-routes.conf и stream-routes.conf"
# conf.d уже включается nginx.conf по умолчанию. stream{} надо подключить вручную.
if ! grep -q "stream-routes.conf" /etc/nginx/nginx.conf; then
    # вставляем перед первым http{}
    sed -i '/^http {/i include /etc/nginx/stream-routes.conf;\n' /etc/nginx/nginx.conf
    log "   -> добавил include /etc/nginx/stream-routes.conf в /etc/nginx/nginx.conf"
fi
# Пустые конфиги — чтобы nginx -t прошёл до того как приложение сгенерирует настоящие
[[ -f /etc/nginx/conf.d/domain-routes.conf ]] || echo "# generated by DomainController" > /etc/nginx/conf.d/domain-routes.conf
[[ -f /etc/nginx/stream-routes.conf ]] || echo "# generated by DomainController" > /etc/nginx/stream-routes.conf

log "7/9 Nginx — frontend для панели на :$PANEL_PORT"
if [[ ! -f /etc/nginx/sites-available/domain-panel.conf ]]; then
    cp deploy/domain-panel.conf /etc/nginx/sites-available/domain-panel.conf
    ln -sf /etc/nginx/sites-available/domain-panel.conf /etc/nginx/sites-enabled/domain-panel.conf
    log "   -> установлен /etc/nginx/sites-available/domain-panel.conf"
    log "   -> !!! отредактируйте allow-листы перед reload'ом"
fi
nginx -t && systemctl reload nginx

log "8/9 systemd unit + logrotate + backup timer + fail2ban + bot-protection"
cp deploy/domain-controller.service /etc/systemd/system/domain-controller.service
cp deploy/domain-controller-backup.service /etc/systemd/system/domain-controller-backup.service
cp deploy/domain-controller-backup.timer /etc/systemd/system/domain-controller-backup.timer
cp deploy/dc-nginx-logs.logrotate /etc/logrotate.d/dc-nginx-logs
cp deploy/fail2ban-dc.filter /etc/fail2ban/filter.d/domain-controller.conf
cp deploy/fail2ban-dc.jail /etc/fail2ban/jail.d/domain-controller.conf
cp deploy/fail2ban-dc-404.filter /etc/fail2ban/filter.d/dc-404-flood.conf
cp deploy/fail2ban-dc-manual.filter /etc/fail2ban/filter.d/dc-manual.conf
cp deploy/fail2ban-dc-manual.jail /etc/fail2ban/jail.d/dc-manual.conf

# Nginx bot-protection: глобальный map в http{} + snippet, который
# включается в каждый server{} проксируемых доменов.
cp deploy/10-bot-protection.conf /etc/nginx/conf.d/10-bot-protection.conf
mkdir -p /etc/nginx/snippets
cp deploy/bot-protect.snippet /etc/nginx/snippets/bot-protect.conf

chmod +x "$INSTALL_DIR/deploy/backup.sh" "$INSTALL_DIR/deploy/apply-uz-cidrs.sh"
mkdir -p "$INSTALL_DIR/backups"
chmod 700 "$INSTALL_DIR/backups"
systemctl daemon-reload
systemctl enable --now domain-controller-backup.timer
systemctl enable --now fail2ban

# 404-flood jail: обогащаем ignoreip всем IP-пулом Узбекистана с ipdeny.com,
# чтобы случайно не забанить реальных юзеров через CGNAT.
"$INSTALL_DIR/deploy/apply-uz-cidrs.sh" || log "WARNING: apply-uz-cidrs.sh вернул ошибку, jail может не активироваться"

systemctl reload fail2ban 2>/dev/null || systemctl restart fail2ban || true

log "9/9 БД — init schema"
# init-db падает без DC_PANEL_SECRET (из-за SECRET_KEY guard в non-DEV).
# .env уже создан выше — читаем его, чтобы передать переменные в flask CLI.
set -a
# shellcheck disable=SC1091
source "$INSTALL_DIR/.env"
set +a
"$INSTALL_DIR/venv/bin/flask" --app "$INSTALL_DIR/app.py" init-db || true

log ""
log "Готово. Следующие шаги:"
log "  1) Отредактируйте $INSTALL_DIR/.env (DC_PANEL_SECRET уже сгенерирован)"
log "  2) Отредактируйте /etc/nginx/sites-available/domain-panel.conf (allow-лист)"
log "  3) sudo $INSTALL_DIR/venv/bin/flask --app $INSTALL_DIR/app.py create-user admin"
log "  4) sudo systemctl enable --now domain-controller"
log "  5) sudo nginx -t && sudo systemctl reload nginx"
log "  6) Откройте http://<IP>:$PANEL_PORT"
log ""
log "Диагностика:  sudo $INSTALL_DIR/venv/bin/flask --app $INSTALL_DIR/app.py doctor"
log "Бэкап вручную: sudo $INSTALL_DIR/deploy/backup.sh"
log "Экспорт/импорт маршрутов: flask ... export-config / import-config"
